#!/usr/bin/env python
# coding=utf-8

import numpy as np
import pylab as pl

def box_muller(n):
    x = np.zeros((n,2))
    y = np.zeros((n,2))

    for i in range(n):
        x[i,:] = np.array([2,2])
        x2 = x[i, 0] ** 2  + x[i, 1] ** 2 
        while x2 > 1:
            x[i,:] = np.random.rand(2) * 2 - 1
            x2 = x[i, 0] ** 2 + x[i, 1] ** 2
        y[i, :] = x[i, :] * np.sqrt( (-2 * np.log(x2)) / x2 )
    y = np.reshape(y, 2 * n, 1)
    return y

if __name__ == '__main__':
    y = box_muller(1000)
    pl.hist(y, normed = 1, fc = 'k')
    x = np.arange(-4, 4, 0.1)
    pl.plot(x, 1 / np.sqrt(2 * np.pi) * np.exp(-0.5 * x ** 2), 'k', lw = 6)
    pl.xlabel('x', fontsize = 24)
    pl.ylabel('x', fontsize = 24)
    pl.show()
